#!/usr/bin/env tsx
/*
 * scripts/r2-setup-test.ts
 *
 * Provisions a SEPARATE Cloudflare R2 bucket (`koom-recordings-test`)
 * used exclusively by the Playwright E2E tests. Shares the same
 * Cloudflare account and same CLOUDFLARE_API_TOKEN as production
 * (both live in web/.env.local), but the test bucket has its own
 * bucket name, its own scoped S3 API token, its own state file
 * (scripts/.r2-state.test.json), and writes its runtime credentials
 * to web/.env.test.local instead of web/.env.local.
 *
 * The whole point of the separate bucket is environment isolation:
 * the E2E test scaffolding uploads and deletes real R2 objects, and
 * we never want a runaway cleanup loop to wipe production recordings.
 * Because Cloudflare R2 S3 API tokens are single-bucket-scoped, the
 * test token genuinely cannot reach `koom-recordings` even if called
 * incorrectly.
 *
 * If web/.env.test.local doesn't exist yet, this script creates it
 * from a template with the known-good local Supabase URL, test port,
 * and fixed test admin secret baked in. The R2_* values are then
 * filled in by the shared provisionR2() helper.
 *
 * Usage:
 *
 *     npm run r2:setup:test
 *
 * Prereqs: web/.env.local must have CLOUDFLARE_API_TOKEN and
 * CLOUDFLARE_ACCOUNT_ID set (i.e. npm run r2:setup has been run).
 */

import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { provisionR2 } from "./lib/r2-provision";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = dirname(SCRIPT_DIR);
const TEST_ENV_PATH = join(REPO_ROOT, "web", ".env.test.local");

/**
 * Template seeded into web/.env.test.local on first run. Contains
 * every non-R2 value the Next.js test server needs. The R2_* values
 * are filled in by provisionR2() afterward.
 *
 * Values chosen so the test environment is fully self-contained:
 *
 *   - DATABASE_URL points at the local Supabase Docker stack. E2E
 *     tests prefix their rows and clean up after themselves, so no
 *     separate test database is needed.
 *   - KOOM_PUBLIC_BASE_URL matches the KOOM_TEST_PORT default used
 *     by the Playwright webServer config. If you override the port,
 *     update this value too.
 *   - KOOM_ADMIN_SECRET is a fixed, intentionally-obvious test
 *     string. Never use this secret outside the E2E test environment.
 */
const TEST_ENV_TEMPLATE = `# koom E2E test environment
#
# This file is auto-generated by scripts/r2-setup-test.ts. Re-run
# that script any time you need to refresh the R2_* credentials.
# Non-R2 values can be edited by hand; they're seeded once on first
# run and not touched again.
#
# Never put real secrets in this file. It exists specifically so the
# Playwright test server runs against an isolated Cloudflare R2
# bucket with a dummy admin secret. Cleaning this file up and
# re-running the script is always safe.

# ─── Postgres ────────────────────────────────────────
# Same local Supabase stack the dev server uses. E2E tests prefix
# their data with "e2e-test-..." and clean up in afterAll, so
# sharing is fine.
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres

# ─── koom app config ─────────────────────────────────
# Must match KOOM_TEST_PORT in playwright.config.ts. Default port
# is 3456. If you set KOOM_TEST_PORT in the environment, update
# this URL to match or Playwright assertions on share URLs will
# fail.
KOOM_PUBLIC_BASE_URL=http://localhost:3456

# Fixed test admin secret. Not used in production. Playwright types
# this exact string into the login form.
KOOM_ADMIN_SECRET=e2e-test-admin-secret-not-for-production

# ─── Cloudflare R2 (TEST bucket) ─────────────────────
# Filled in by scripts/r2-setup-test.ts. The bucket is
# koom-recordings-test, scoped by its own S3 token. Do not edit by
# hand — re-run the script instead.
R2_BUCKET=
R2_ACCOUNT_ID=
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_PUBLIC_BASE_URL=
`;

async function main(): Promise<void> {
  // Seed the output env file from the template on first run.
  if (!existsSync(TEST_ENV_PATH)) {
    process.stdout.write(`Creating ${TEST_ENV_PATH} from template…\n`);
    await writeFile(TEST_ENV_PATH, TEST_ENV_TEMPLATE, "utf-8");
  }

  await provisionR2({
    displayName: "koom R2 Test Bucket Setup",
    bucketName: "koom-recordings-test",
    runtimeTokenName: "koom-runtime-r2-test",
    stateFilePath: join(SCRIPT_DIR, ".r2-state.test.json"),
    credentialsEnvPath: join(REPO_ROOT, "web", ".env.local"),
    outputEnvPath: TEST_ENV_PATH,
  });
}

main().catch((err) => {
  process.stderr.write(
    `\nUnexpected error: ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`,
  );
  process.exit(1);
});
