-- 20260408000000_create_recordings.sql
--
-- First migration for koom. Creates the single `recordings` table
-- that stores all metadata the app needs. Video bytes live in
-- Cloudflare R2 keyed by `recordingId`; this table is the source of
-- truth for everything else (status, timestamps, size, etc).
--
-- Design notes:
--   - `id` is a UUID generated by the backend at upload init time.
--     Stored as TEXT rather than UUID so it's trivially portable and
--     easy to inspect by hand. Primary key.
--   - `status` is a lifecycle flag: 'pending' during upload, flipped
--     to 'complete' once the R2 HEAD in completeUpload succeeds.
--     Listing queries filter to 'complete' so mid-upload rows never
--     leak into the UI.
--   - `duration_seconds` is nullable because AVFoundation may not
--     always yield a usable duration; the UI degrades gracefully.
--   - `size_bytes` is BIGINT because recordings can be multi-GB.
--   - The covering index on (status, created_at DESC) is sized for
--     the only query shape that matters for listings at single-tenant
--     scale: `WHERE status = 'complete' ORDER BY created_at DESC`.

CREATE TABLE recordings (
    id                TEXT PRIMARY KEY,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    status            TEXT NOT NULL CHECK (status IN ('pending', 'complete')),
    title             TEXT,
    original_filename TEXT NOT NULL,
    duration_seconds  REAL,
    size_bytes        BIGINT NOT NULL CHECK (size_bytes >= 0),
    content_type      TEXT NOT NULL DEFAULT 'video/mp4',
    bucket            TEXT NOT NULL,
    object_key        TEXT NOT NULL
);

CREATE INDEX recordings_status_created_at_idx
    ON recordings (status, created_at DESC);
